name: Deploy to Astronomer

on:
  push:
    branches:
      - main   # triggers on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.4
        with:
          deployment-id: ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
          api-token: ${{ secrets.ASTRONOMER_API_TOKEN }}
